version: "3.2"
services:
  forseti:
    image: forseti:0.3.0
    ports:
      - target: 8080
        published: 8088
    environment:
      - GIN_MODE=release
      - TZ=Europe/Paris
      - FORSETI_LOG_LEVEL=info

      # Departures parameters
      - FORSETI_DEPARTURES_URI=
      - FORSETI_DEPARTURES_REFRESH=

      # Parkings parameters
      - FORSETI_PARKINGS_URI=
      - FORSETI_PARKINGS_REFRESH=

      # Equipments parameters
      - FORSETI_EQUIPMENTS_URI=
      - FORSETI_EQUIPMENTS_REFRESH=

      # Free floatings parameters
      - FORSETI_FREE_FLOATINGS_URI=
      - FORSETI_FREE_FLOATINGS_TOKEN=
      - FORSETI_FREE_FLOATINGS_REFRESH=300s
      - FORSETI_FREE_FLOATINGS_REFRESH_ACTIVE=False

      # Occupancies parameters
      - FORSETI_OCCUPANCY_SERVICE_REFRESH_ACTIVE=False
      - FORSETI_OCCUPANCY_FILES_URI=file:///data
      - FORSETI_OCCUPANCY_NAVITIA_URI=
      - FORSETI_OCCUPANCY_SERVICE_URI=
      - FORSETI_OCCUPANCY_NAVITIA_TOKEN=
      - FORSETI_OCCUPANCY_SERVICE_TOKEN=
      - FORSETI_OCCUPANCY_REFRESH=300s
      - FORSETI_ROUTESCHEDULE_REFRESH=3600s

    volumes:
      - ~/workspace/data/forseti:/data

    deploy:
      resources:
        limits:
          memory: 1024M
