version: "3.2"
services:
  forseti:
    image: navitia/forseti:master
    ports:
      - target: 8080
        published: 8088
    environment:
      - GIN_MODE=release
      - TZ=Europe/Paris
      - FORSETI_LOG_LEVEL=info

      # timezone location parameter
      - FORSETI_TIMEZONE_LOCATION=Europe/Paris

      # Departures parameters
      - FORSETI_DEPARTURES_URI=
      - FORSETI_DEPARTURES_REFRESH=

      # Parkings parameters
      - FORSETI_PARKINGS_URI=
      - FORSETI_PARKINGS_REFRESH=

      # Equipments parameters
      - FORSETI_EQUIPMENTS_URI=
      - FORSETI_EQUIPMENTS_REFRESH=

      # Free floatings parameters
      - FORSETI_FREE_FLOATINGS_URI=
      - FORSETI_FREE_FLOATINGS_TOKEN=
      - FORSETI_FREE_FLOATINGS_REFRESH=300s
      - FORSETI_FREE_FLOATINGS_REFRESH_ACTIVE=False

      # Occupancies and Positions parameters
      - FORSETI_CONNECTOR_TYPE=gtfsrt

      # Occupancies parameters
      #- FORSETI_OCCUPANCY_SERVICE_REFRESH_ACTIVE=true
      #- FORSETI_OCCUPANCY_FILES_URI=file:///data
      #- FORSETI_OCCUPANCY_NAVITIA_URI=https://api.navitia.io/v1/coverage/ca-qc-sherbrooke
      #- FORSETI_OCCUPANCY_SERVICE_URI=http://gtfsrt.stsherbrooke.civilia.ca/pb/vehiclePositions.pb
      #- FORSETI_OCCUPANCY_NAVITIA_TOKEN=6a92dfdc-155d-4ea3-8775-6f93a1efc498
      #- FORSETI_OCCUPANCY_SERVICE_TOKEN=
      #- FORSETI_OCCUPANCY_REFRESH=300s
      #- FORSETI_ROUTESCHEDULE_REFRESH=3600s
      
      # Positions parameters
      - FORSETI_POSITIONS_SERVICE_REFRESH_ACTIVE=true
      - FORSETI_POSITIONS_FILES_URI=file:///data
      - FORSETI_POSITIONS_SERVICE_URI=http://gtfsrt.stsherbrooke.civilia.ca/pb/vehiclePositions.pb
      - FORSETI_POSITIONS_SERVICE_TOKEN=
      - FORSETI_POSITIONS_REFRESH=300s

    volumes:
      - ~/workspace/data/forseti:/data

    deploy:
      resources:
        limits:
          memory: 1024M
