name: CI

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare Env
        run: export GO111MODULE=on

      - name: Install all the build and lint dependencies
        run: make setup

      - name: Install linter
        run: make linter-install

      - name: Run all the tests and code checks
        run: make ci

      - name: Get branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Upload coverage report
        if: env.BRANCH_NAME == 'master'
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
